### LOGIN
POST http://localhost:5249/api/auth/login
Content-Type: application/json

{
  "email": "krisp@test.com",
  "password": "123456"
}

### GET CURRENT USER
GET http://localhost:5249/api/auth/student/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjFkOTMyMGE1LWZkNzAtNGM4Mi04YjdkLTgzMTVkMjJmYzY2MyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlN0dWRlbnQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJrcmlzcEB0ZXN0LmNvbSIsImV4cCI6MTc3MzkyMjg1MywiaXNzIjoiQ2FtcHVzRVJQIiwiYXVkIjoiQ2FtcHVzRVJQVXNlcnMifQ.IvZHXjcspWFPy2pGkuH6iTcTJHghugmr0jiEJlu26sU